// ecozeAI Cloud Functions v2
//
// ****************************************************************************************
// *  COPYRIGHT (C) 2025 ECOZE LTD. ALL RIGHTS RESERVED.
// *
// *  CONFIDENTIAL AND PROPRIETARY INFORMATION
// *
// *  The intellectual and technical concepts contained herein are proprietary to
// *  ECOZE Ltd and are protected by trade secret and copyright laws
// *  of the United Kingdom and other international jurisdictions.
// *
// *  Any unauthorized use, reproduction, dissemination, distribution, reverse 
// *  engineering, or modification of this material, in whole or in part, without 
// *  the prior written permission of ECOZE Ltd is strictly prohibited and 
// *  constitutes a violation of applicable laws.
// *
// *  THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// *  FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL
// *  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// *  THE SOFTWARE.
// ****************************************************************************************
const {
    cf1,
    cf2,
    cf3,
    cf4,
    cf5,
    cf6,
    cf7,
    cf8,
    cf9,
    cf10,
    cf11,
    cf12,
    cf13,
    cf14,
    cf15,
    cf16,
    cf17,
    cf18,
    cf19,
    cf20,
    cf21,
    cf22,
    cf23,
    cf24,
    cf25,
    cf26,
    cf27,
    cf28,
    cf29,
    cf30,
    cf31,
    cf32,
    cf33,
    cf34,
    cf35,
    cf36,
    cf37,
    cf38,
    cf39,
    cf40,
    cf41,
    cf42,
    cf43,
    cf44,
    cf45,
    cf46,
    cf47,
    cf48,
    cf49,
    cf50,
    cf51,
    cf52,
    cf53,
    cf54,
    cf55,
    cf56,
    cf57,
    cf58,
    cf59,
    cf60,
    cf61
} = require("./src/cloudfunctions");

module.exports = {
    cf1,
    cf2,
    cf3,
    cf4,
    cf5,
    cf6,
    cf7,
    cf8,
    cf9,
    cf10,
    cf11,
    cf12,
    cf13,
    cf14,
    cf15,
    cf16,
    cf17,
    cf18,
    cf19,
    cf20,
    cf21,
    cf22,
    cf23,
    cf24,
    cf25,
    cf26,
    cf27,
    cf28,
    cf29,
    cf30,
    cf31,
    cf32,
    cf33,
    cf34,
    cf35,
    cf36,
    cf37,
    cf38,
    cf39,
    cf40,
    cf41,
    cf42,
    cf43,
    cf44,
    cf45,
    cf46,
    cf47,
    cf48,
    cf49,
    cf50,
    cf51,
    cf52,
    cf53,
    cf54,
    cf55,
    cf56,
    cf57,
    cf58,
    cf59,
    cf60,
    cf61
};
